name: "Deploy version tag"

on:
  workflow_dispatch: {}
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # pull all commits so git info can be pulled for all files

      - name: Parse Semver
        id: semver
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ github.ref_name }}
          version_extractor_regex: v(.*)

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Cache Dependencies
        id: pip-cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Setup doc deploy
        run: |
          git config --global user.name Actions Builder
          git config --global user.email builder@github.com

      - name: Deploy to gh-pages branch
        run: mike deploy --push ${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}

      ####### Update the "latest" alias #######
      - name: List version tags
        run: git tag --list v[0-9]*

      - name: Get highest version tag
        id: get-latest
        run: |
          echo ::set-output name=latest-tag::$(git tag --list v[0-9]* | tail -n 1)
          echo using latest tag of $(git tag --list v[0-9]* | tail -n 1)

      - name: Get current "latest" real version
        id: mike-latest
        run: |
          mv=$(mike list --json | jq --raw-output '.[] | select( .aliases | index("latest") ).version')
          echo ::set-output name=latest-version::$mv
          echo version "$mv" currently has the "latest" alias

      - name: Parse Latest Semver
        id: semver-latest
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ steps.get-latest.outputs.latest-tag }}
          version_extractor_regex: v(.*)

      - name: Show Parsed versions
        id: versions
        run: |
          echo ::set-output name=tag::${{ steps.semver-latest.outputs.major }}.${{ steps.semver-latest.outputs.minor }}
          echo ::set-output name=mike::${{ steps.mike-latest.outputs.latest-version }}
          echo latest tag version: ${{ steps.semver-latest.outputs.major }}.${{ steps.semver-latest.outputs.minor }}
          echo Mike "latest" version: ${{ steps.mike-latest.outputs.latest-version }}

      - name: Show mike versions before change
        run: mike list

      - name: Update "latest"
        if: ${{ steps.versions.outputs.mike != steps.versions.outputs.tag }}
        run: mike alias --update-aliases --push ${{ steps.versions.outputs.tag }} latest

      - name: Show mike versions after change
        run: mike list
