name: "Deploy main branch"

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # pull all commits so git info can be pulled for all files

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Cache Dependencies
        id: pip-cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Setup doc deploy
        run: |
          git config --global user.name "Actions Builder"
          git config --global user.email builder@github.com

      - name: Deploy to gh-pages branch
        run: mike deploy --push dev
